// TEST DATA

export const jackets = [
  {
    id: "1",
    title: "Producto 1",
    description: "Este es el producto 1",
    pictureName: "Img-producto-1.jpg",
    pictureUrl:
      "https://i.pinimg.com/236x/9c/bd/fa/9cbdfa01d6edf39ef6bf265c756e00f2--down-jackets-black-jackets.jpg",
    price: 3000,
    stock: 10,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 10,
    filter: {
      sex: "male",
    },
    category: "jackets",
    sizes: ["M", "L", "XL"],
    colors: ["gray", "black", "beige"],
  },
  {
    id: "2",
    title: "Producto 2",
    description: "Este es el producto 2",
    pictureName: "Img-product-2.jpg",
    pictureUrl:
      "https://cdn.shopify.com/s/files/1/0034/5459/9217/products/product-image-554242478_1024x1024@2x.jpg?v=1571720317",
    price: 3000,
    stock: 10,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 10,
    filter: {
      sex: "male",
    },
    category: "jackets",
    sizes: ["M", "L", "XL"],
    colors: ["green", "black", "beige", "white"],
  },
  {
    id: "3",
    title: "Producto 3",
    description: "Este es el producto 3",
    pictureName: "Img-product-3.jpg",
    pictureUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5A144CiT7efJ4I1_aUMWAfHMhpNjqLsJ60g&usqp=CAU",
    price: 3000,
    stock: 10,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 10,
    filter: {
      sex: "male",
    },
    category: "jackets",
    sizes: ["M", "L", "XL"],
    colors: ["cyan", "red", "black", "white", "yellow", "orange", "lime"],
  },
  {
    id: "4",
    title: "Producto 4",
    description: "Este es el producto 4",
    pictureName: "Img-product-4.jpg",
    pictureUrl:
      "https://www.dhresource.com/0x0/f2/albu/g6/M00/F5/27/rBVaSFu_RPuAbYuaAAGva5aGSfI777.jpg/plus-size-coat-women-clothes-winter-2018.jpg",
    price: 3000,
    stock: 10,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 10,
    filter: {
      sex: "female",
    },
    category: "jackets",
    sizes: ["S", "M", "L"],
    colors: ["gray", "black", "white", "pink", "brown"],
  },
  {
    id: "5",
    title: "Producto 5",
    description: "Este es el producto 5",
    pictureName: "Img-product-4.jpg",
    pictureUrl:
      "https://www.dhresource.com/0x0/f2/albu/g6/M01/1C/E5/rBVaSFvhfJKAMHFtAAD8QbHExK8807.jpg",
    price: 3000,
    stock: 10,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 10,
    filter: {
      sex: "female",
    },
    category: "jackets",
    sizes: ["S", "M", "L"],
    colors: ["brown", "white", "blue", "red", "black", "pink"],
  },
  {
    id: "6",
    title: "Producto 6",
    description: "Este es el producto 6",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/4976b06da55d4f5bbe92aac5015e519a_9366/Buzo_con_Capucha_Linear_Negro_FM0772_01_laydown.jpg",
    price: 3000,
    stock: 10,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 10,
    filter: {
      sex: "all",
    },
    category: "jackets",
    sizes: ["S", "M", "L", "XL"],
    colors: ["white-blue", "gray-blue", "gray-red", "white-black"],
  },
  {
    id: "7",
    title: "Producto 7",
    description: "Este es el producto 7",
    pictureName: "Img-producto-7.jpg",
    pictureUrl:
      "https://i.pinimg.com/originals/5d/32/e0/5d32e0686d553746b55ffe6df1e2a752.jpg",
    price: 4000,
    stock: 40,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 40,
    filter: {
      sex: "all",
    },
    category: "jackets",
    sizes: ["S", "M", "L", "XL"],
    colors: ["blue"],
  },
]

export const shirts = [
  {
    id: "8",
    title: "Producto 8",
    description: "Este es el producto 8",
    pictureName: "Img-producto-7.jpg",
    pictureUrl:
      "https://d3295hraz5fimx.cloudfront.net/19036-product_lg/remera-de-hombre-rider.jpg",
    price: 4000,
    stock: 40,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 40,
    filter: {
      sex: "male",
    },
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["gray", "blue", "white", "black"],
  },
  {
    id: "9",
    title: "Producto 9",
    description: "Este es el producto 9",
    pictureName: "Img-producto-7.jpg",
    pictureUrl:
      "https://www.digitalsport.com.ar/files/products/594d6b7eb853a-435243-1200x1200.jpg",
    price: 4000,
    stock: 40,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 40,
    filter: {
      sex: "male",
    },
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "blue"],
  },
  {
    id: "10",
    title: "Producto 10",
    description: "Este es el producto 10",
    pictureName: "Img-producto-7.jpg",
    pictureUrl:
      "https://d26lpennugtm8s.cloudfront.net/stores/187/269/products/ranglan-hombre1-27d3334ae286fd5e8915307250822298-640-0.jpg",
    price: 4000,
    stock: 40,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 40,
    filter: {
      sex: "male",
    },
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black-white"],
  },
  {
    id: "11",
    title: "Producto 11",
    description: "Este es el producto 11",
    pictureName: "Img-producto-5.jpg",
    pictureUrl:
      "https://s1.eestatic.com/2019/08/15/omicrono/omicrono_421718717_132328427_1024x576.jpg",
    price: 5000,
    stock: 50,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 50,
    filter: {
      sex: "all",
    },
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black"],
  },
  {
    id: "12",
    title: "Producto 12",
    description: "Este es el producto 12",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://i.pinimg.com/originals/f1/ae/04/f1ae0491447558a46a3bede6df69934a.jpg",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "all",
    },
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "white"],
  },
  {
    id: "13",
    title: "Producto 13",
    description: "Este es el producto 13",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://http2.mlstatic.com/D_NQ_NP_622743-MLA41406178573_042020-W.jpg",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "female",
    },
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["blue", "white", "black", "pink", "yellow", "red", "gray"],
  },
  {
    id: "14",
    title: "Producto 14",
    description: "Este es el producto 14",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://vermediamanager.prod.ingecloud.com/MediaFiles/Topyed/2020/7_30/0/22/104/1468506.jpg",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "female",
    },
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: [],
  },
  {
    id: "15",
    title: "Producto 15",
    description: "Este es el producto 15",
    pictureName: "Img-producto-6.jpg",
    pictureUrl: "https://bananashake.com.ar/upload/6961754690.jpg",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "female",
    },
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "pink", "orange", "blue"],
  },
]

export const shoes = [
  {
    id: "16",
    title: "Producto 16",
    description: "Este es el producto 16",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://ae01.alicdn.com/kf/HTB1.XQZdBKw3KVjSZTEq6AuRpXaE/NIKE-Zapatillas-Mujer-WMNS-NIKE-LD-RUNNER-Atletismo-y-running-Summit-White-Laser-Pink-Wolf-G.jpg_q50.jpg",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "female",
    },
    category: "shoes",
    sizes: ["30", "32", "35", "38"],
    colors: ["white-pink"],
  },
  {
    id: "17",
    title: "Producto 17",
    description: "Este es el producto 17",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://www.instyle.es/medio/2019/10/11/nike-air-max-270-react_f029b57b_642x803.png",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "all",
    },
    category: "shoes",
    sizes: ["35", "38", "40", "42", "43"],
    colors: ["pink"],
  },
  {
    id: "18",
    title: "Producto 18",
    description: "Este es el producto 18",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4ZjEbcXj0GLh3HiKqgsjzy_KpftdA5vmTuQ&usqp=CAU",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "all",
    },
    category: "shoes",
    sizes: ["40", "42", "43"],
    colors: ["white", "gray", "teal"],
  },
]

export const accesories = [
  {
    id: "19",
    title: "Producto 19",
    description: "Este es el producto 19",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://d26lpennugtm8s.cloudfront.net/stores/966/070/products/th1791651_11-248a4156b9f48560a515914782870287-1024-1024.jpg",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "male",
    },
    category: "accesories",
    sizes: [],
    colors: ["black"],
  },
  {
    id: "20",
    title: "Producto 20",
    description: "Este es el producto 20",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://cdn.shopify.com/s/files/1/0050/4106/1977/products/16641-522_1500x1500_0769613e-bbf7-4245-8f4f-0199f08564fb_393x@3x.progressive.jpg?v=1566932379",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "male",
    },
    category: "accesories",
    sizes: [],
    colors: ["black-brown"],
  },
  {
    id: "21",
    title: "Producto 21",
    description: "Este es el producto 21",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://www.joyeriaoliverdelpino.com/2469-large_default/reloj-mujer-calvin-klein-seduce.jpg",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "female",
    },
    category: "accesories",
    sizes: [],
    colors: ["pink"],
  },
  {
    id: "22",
    title: "Producto 22",
    description: "Este es el producto 22",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://artecolorvisual.com/wp-content/uploads/gorra-trucker-negra-con-visera-curva.jpg",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "female",
    },
    category: "accesories",
    sizes: [],
    colors: ["black", "red", "blue"],
  },
  {
    id: "23",
    title: "Producto 23",
    description: "Este es el producto 23",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://www.eobuv.cz/media/catalog/product/cache/image/650x650/0/0/0000200446578_01_pz.jpg",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
    filter: {
      sex: "all",
    },
    category: "accesories",
    sizes: [],
    colors: ["black", "red", "blue", "white"],
  },
]

export const PRODUCTS = [...jackets, ...shirts, ...shoes, ...accesories]
