// TEST DATA

export const PRODUCTS = [
  {
    id: "1",
    title: "Producto 1",
    description: "Este es el producto 1",
    pictureName: "Img-producto-1.jpg",
    pictureUrl:
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/4976b06da55d4f5bbe92aac5015e519a_9366/Buzo_con_Capucha_Linear_Negro_FM0772_01_laydown.jpg",
    price: 3000,
    stock: 10,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 10,
  },
  {
    id: "2",
    title: "Producto 2",
    description: "Este es el producto 2",
    pictureName: "Img-producto-2.jpg",
    pictureUrl:
      "https://i.pinimg.com/236x/7a/b9/46/7ab946a32295b20e547078c5f5578c05.jpg",
    price: 2000,
    stock: 20,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 20,
  },
  {
    id: "3",
    title: "Producto 3",
    description: "Este es el producto 3",
    pictureName: "Img-producto-3.jpg",
    pictureUrl:
      "https://www.ropadetrabajohernandez.com/392-home_default/casaca-cuello-pico-velilla-sanitario-limpieza.jpg",
    price: 3000,
    stock: 30,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 30,
  },
  {
    id: "4",
    title: "Producto 4",
    description: "Este es el producto 4",
    pictureName: "Img-producto-4.jpg",
    pictureUrl:
      "https://i.pinimg.com/originals/5d/32/e0/5d32e0686d553746b55ffe6df1e2a752.jpg",
    price: 4000,
    stock: 40,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 40,
  },
  {
    id: "5",
    title: "Producto 5",
    description: "Este es el producto 5",
    pictureName: "Img-producto-5.jpg",
    pictureUrl:
      "https://s1.eestatic.com/2019/08/15/omicrono/omicrono_421718717_132328427_1024x576.jpg",
    price: 5000,
    stock: 50,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 50,
  },
  {
    id: "6",
    title: "Producto 6",
    description: "Este es el producto 6",
    pictureName: "Img-producto-6.jpg",
    pictureUrl:
      "https://i.pinimg.com/originals/f1/ae/04/f1ae0491447558a46a3bede6df69934a.jpg",
    price: 6000,
    stock: 60,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 60,
  },
  {
    id: "7",
    title: "Producto 7",
    description: "Este es el producto 7",
    pictureName: "Img-producto-7.jpg",
    pictureUrl: "",
    price: 7000,
    stock: 7,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 70,
  },
  {
    id: "8",
    title: "Producto 8",
    description: "Este es el producto 8",
    pictureName: "Img-producto-8.jpg",
    pictureUrl: "",
    price: 8000,
    stock: 8,
    brand: "Marca del producto",
    model: "Modelo del producto",
    calification: 80,
  },
]
